# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFirstApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyFirstApp

 pod 'SpinKit', '~> 1.1'
 pod 'MBProgressHUD'
end
